{
  "languague": "angular",
  "angular": [
    "1.5.8",
    "1.5.9"
  ],
  "before-script": [
    "bower install --no-interaction"
  ],
  "script": [
    "JavaScript/app.js"
  ],
  "language": "ruby",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
